config/routes.rb
Dacapo::Application.routes.draw do

  
   controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
    end
        
  resources :password_resets

scope '(:locale)' do
    resources :students
    resources :periods
    resources :payments
    resources :payment_types
    resources :users
    resources :subjects do
      collection do
          get :periods
          get :groups
          post :addtomajor
          post :addtoperiod
          post :addtogroup
          get :preview
          post :preview
          get :inscripccion
          post :inscribir
          get :calificaciones
          post :califas
          post :grades
          
      end
    end
    resources :majors
    resources :groups
    resources :shifts
    resources :minors do
      collection do
          post :addminor
      end
    end
    resources :admins
    resources :tetramods
    resources :superadmins
    resources :teachers
    resources :costs
end

end

app/models/superadmin.rb
class Superadmin < ActiveRecord::Base
  belongs_to :user
  attr_accessible :fecha_nac, :nombre, :user_id, :user_attributes, :fec_in, :apmat, :appat, :direccion,
  :telefono1, :telefono2, :telefono3
  
  
  validates :nombre,  :presence => true
  validates_associated :user
  accepts_nested_attributes_for :user
  attr_accessible :fecha_nac, :nombre, :user_id, :user_attributes
end

app/controllers/superadmins_controller.rb
class SuperadminsController < ApplicationController
  # GET /superadmins
  # GET /superadmins.json
  def index
    @superadmins = Superadmin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @superadmins }
    end
  end

  # GET /superadmins/1
  # GET /superadmins/1.json
  def show
    @superadmin = Superadmin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @superadmin }
    end
  end

  # GET /superadmins/new
  # GET /superadmins/new.json
  def new
    @user = User.new
    @superadmin = Superadmin.new
    @superadmin.user = @user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @superadmin }
    end
  end

  # GET /superadmins/1/edit
  def edit
    @superadmin = Superadmin.find(params[:id])
    @user = @superadmin.user
  end

  # POST /superadmins
  # POST /superadmins.json
  def create
    @user = User.new(params[:superadmin][:user_attributes])
    @superadmin = Superadmin.new(params[:superadmin])
    @superadmin.user = @user

    respond_to do |format|
      if @superadmin.save
        format.html { redirect_to @superadmin, notice: 'Superadmin was successfully created.' }
        format.json { render json: @superadmin, status: :created, location: @superadmin }
      else
        format.html { render action: "new" }
        format.json { render json: @superadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /superadmins/1
  # PUT /superadmins/1.json
  def update
    @superadmin = Superadmin.find(params[:id])

    respond_to do |format|
      if @superadmin.update_attributes(params[:superadmin]) and
        @superadmin.user.update_attributes(params[:superadmin][:user_attributes])
        format.html { redirect_to @superadmin, notice: 'Superadmin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @superadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superadmins/1
  # DELETE /superadmins/1.json
  def destroy
    @superadmin = Superadmin.find(params[:id])
    id = @admin.user_id
    @user = User.find(id)
    @user.destroy
    
    respond_to do |format|
      format.html { redirect_to superadmins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/superadmins_helper.rb
module SuperadminsHelper
end

app/views/superadmins/_form.html.erb
<%= form_for(@superadmin) do |f| %>
  <% if @superadmin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@superadmin.errors.count, "error") %> prohibited this superadmin from being saved:</h2>

      <ul>
      <% @superadmin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
<%= f.fields_for :user do |ef| %>
<div class="control-group">
    <%= ef.label :username, :class=>"control-label" %>
   <div class="controls">
    <%= ef.text_field :username %>
  </div>
<div class="control-group">
    <%= ef.label :password, :class=>"control-label" %>
   <div class="controls">
    <%= ef.password_field :password %>
</div>
<div class="control-group">
    <%= ef.label :password_confirmation, :class=>"control-label" %>
   <div class="controls">
    <%= ef.password_field :password_confirmation %>
</div>
<div class="control-group">
    <%= ef.label :email, :class=>"control-label" %>
   <div class="controls">
    <%= ef.text_field :email %>
</div>
<%= ef.hidden_field :rol , :value =>"SuperAdmin"  %>
</div>
<%- end %>

  <div class="field">
    <%= f.label :fecha_nac %><br />
    <%= f.date_select :fecha_nac, :start_year => 1950 %>
  </div>

  <div class="field">
    <%= f.label :fec_in %><br />
    <%= f.date_select :fec_in, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :telefono1 %><br />
    <%= f.text_field :telefono1 %>
  </div>
  <div class="field">
    <%= f.label :telefono2 %><br />
    <%= f.text_field :telefono2 %>
  </div>
  <div class="field">
    <%= f.label :telefono3 %><br />
    <%= f.text_field :telefono3 %>
  </div>
 <div class="field">
    <%= f.label :estatus %><br />
	<select id="estatus" name="estatus">
	  <option value="1">ACTIVO</option>
	  <option value="0">BAJA</option>
	  <option value="0">BLOQUEADO</option>
	</select>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/superadmins/edit.html.erb
<h1>Editing superadmin</h1>

<%= render 'form' %>

<%= link_to 'Show', @superadmin %> |
<%= link_to 'Back', superadmins_path %>

app/views/superadmins/index.html.erb
<h1>Administradores</h1>

<table class="table table-striped table-bordered table-condensed" style="table-layout:fixed;word-wrap:break-word;">
  <tr>
	<th style="text-align:center;">Nomina</th>
    <th style="text-align:center;">Nombre</th>
    <th></th>
    <th></th>
  </tr>

<% @superadmins.each do |superadmin| %>
  <tr>
	<td style="text-align:center;"><%= link_to superadmin.user.username, superadmin %></td>
    <td style="text-align:center;"><%= superadmin.nombre + " " + superadmin.appat + " " + superadmin.apmat %></td>
    <td width="75"><%= link_to '<i class="icon-edit icon-white"></i> Editar'.html_safe, edit_superadmin_path(superadmin) %></td>
   <td width="87"><%= link_to '<i class="icon-trash icon-white"></i> Eliminar'.html_safe, superadmin, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '<i class="icon-pencil icon-white"></i> Agregar Administrador'.html_safe, new_superadmin_path, :class => 'btn btn-info' %>

app/views/superadmins/new.html.erb
<h1>New superadmin</h1>

<%= render 'form' %>

<%= link_to 'Back', superadmins_path %>

app/views/superadmins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @superadmin.nombre %>
</p>

<p>
  <b>Fecha nac:</b>
  <%= @superadmin.fecha_nac %>
</p>

<p>
  <b>User:</b>
  <%= @superadmin.user_id %>
</p>


<%= link_to 'Edit', edit_superadmin_path(@superadmin) %> |
<%= link_to 'Back', superadmins_path %>