config/routes.rb
Dacapo::Application.routes.draw do

  
   controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
    end
        
  resources :password_resets

scope '(:locale)' do
    resources :students
    resources :periods
    resources :payments
    resources :payment_types
    resources :users
    resources :subjects do
      collection do
          get :periods
          get :groups
          post :addtomajor
          post :addtoperiod
          post :addtogroup
          get :preview
          post :preview
          get :inscripccion
          post :inscribir
          get :calificaciones
          post :califas
          post :grades
          
      end
    end
    resources :majors
    resources :groups
    resources :shifts
    resources :minors do
      collection do
          post :addminor
      end
    end
    resources :admins
    resources :tetramods
    resources :superadmins
    resources :teachers
    resources :costs
end

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  has_many :pay_item
  
  attr_accessible :descripcion, :modificable, :monto, :obligatorio, :seguridad, :tipo, :est
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @costs }
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/new
  # GET /costs/new.json
  def new
    @cost = Cost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.find(params[:id])
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(params[:cost])

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render json: @cost, status: :created, location: @cost }
      else
        format.html { render action: "new" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /costs/1
  # PUT /costs/1.json
  def update
    @cost = Cost.find(params[:id])

    respond_to do |format|
      if @cost.update_attributes(params[:cost])
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
	<select id="tipo" name="tipo">
	  <option value="0">-</option>
	  <option value="1">+</option>
	</select>  
	</div>
  <div class="field">
    <%= f.label :monto %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    Obligatorio <%= f.check_box :obligatorio, {}, 1, 0 %> 
	Seguridad	<%= f.check_box :seguridad, {}, 1, 0 %>
	Modificable  <%= f.check_box :modificable, {}, 1, 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<h1>Listing costs</h1>

<table>
  <tr>
    <th>Descripcion</th>
    <th>Tipo</th>
    <th>Monto</th>
    <th>Obligatorio</th>
    <th>Seguridad</th>
    <th>Modificable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @costs.each do |cost| %>
  <tr>
    <td><%= cost.descripcion %></td>
    <td><%= cost.tipo %></td>
    <td><%= cost.monto %></td>
    <td><%= cost.obligatorio %></td>
    <td><%= cost.seguridad %></td>
    <td><%= cost.modificable %></td>
    <td><%= link_to 'Show', cost %></td>
    <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
    <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @cost.descripcion %>
</p>

<p>
  <b>Tipo:</b>
  <%= @cost.tipo %>
</p>

<p>
  <b>Monto:</b>
  <%= @cost.monto %>
</p>

<p>
  <b>Obligatorio:</b>
  <%= @cost.obligatorio %>
</p>

<p>
  <b>Seguridad:</b>
  <%= @cost.seguridad %>
</p>

<p>
  <b>Modificable:</b>
  <%= @cost.modificable %>
</p>


<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>