config/routes.rb
Dacapo::Application.routes.draw do

  
   controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
    end
        
  resources :password_resets

scope '(:locale)' do
    resources :students
    resources :periods
    resources :payments
    resources :payment_types
    resources :users
    resources :subjects do
      collection do
          get :periods
          get :groups
          post :addtomajor
          post :addtoperiod
          post :addtogroup
          get :preview
          post :preview
          get :inscripccion
          post :inscribir
          get :calificaciones
          post :califas
          post :grades
          
      end
    end
    resources :majors
    resources :groups
    resources :shifts
    resources :minors do
      collection do
          post :addminor
      end
    end
    resources :admins
    resources :tetramods
    resources :superadmins
    resources :teachers
    resources :costs
end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :user
  
  
  
  attr_accessible :apmat, :appat, :direccion, :fecha_nac, :nombre, :fec_in,:estatus, 
  :telefono1, :telefono2, :telefono3, :user_id, :user_attributes
  
  
  validates :nombre,:presence => true
  validates_associated :user
  accepts_nested_attributes_for :user
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @user = User.new
    @teacher = Teacher.new
    @teacher.user = @user
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
    @user = @teacher.user
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @user = User.new(params[:teacher][:user_attributes])
    @teacher = Teacher.new(params[:teacher])
    @teacher.user = @user

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher]) and
        @teacher.user.update_attributes(params[:teacher][:user_attributes])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    id = @student.user_id
    @user = User.find(id)
    @user.destroy
     
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<% o =  [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten  
   string  =  (0..8).map{ o[rand(o.length)]  }.join
%>

<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :appat %><br />
    <%= f.text_field :appat %>
  </div>
  <div class="field">
    <%= f.label :apmat %><br />
    <%= f.text_field :apmat %>
  </div>

<%= f.fields_for :user do |ef| %>

<div class="control-group">
	<div class="control-group">
	    <%= ef.label :username, :class=>"control-label" %>
	   <div class="controls">
	    <%= ef.text_field :username %>
	  </div>
    <%= ef.label :email, :class=>"control-label" %>
   <div class="controls">
    <%= ef.text_field :email %>
  </div>
<%= ef.hidden_field :rol , :value =>"Teacher"  %>
<%= ef.hidden_field :password, :value => string %>
<%= ef.hidden_field :password_confirmation, :value => string %>
</div>
<%- end %>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :fecha_nac %><br />
    <%= f.date_select :fecha_nac, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :fec_in %><br />
    <%= f.date_select :fec_in, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :telefono1 %><br />
    <%= f.text_field :telefono1 %>
  </div>
  <div class="field">
    <%= f.label :telefono2 %><br />
    <%= f.text_field :telefono2 %>
  </div>
  <div class="field">
    <%= f.label :telefono3 %><br />
    <%= f.text_field :telefono3 %>
  </div>
 <div class="field">
    <%= f.label :estatus %><br />
	<select id="estatus" name="estatus">
	  <option value="1">ACTIVO</option>
	  <option value="0">BAJA</option>
	  <option value="2">BLOQUEADO</option>
	</select>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/teachers/_form_edit.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :appat %><br />
    <%= f.text_field :appat %>
  </div>
  <div class="field">
    <%= f.label :apmat %><br />
    <%= f.text_field :apmat %>
  </div>

<%= f.fields_for :user do |ef| %>

<div class="control-group">
    <%= ef.label :email, :class=>"control-label" %>
   <div class="controls">
    <%= ef.text_field :email %>
  </div>
</div>
<div class="control-group">
    <%= ef.label :username, :class=>"control-label" %>
   <div class="controls">
    <%= ef.text_field :username %>
  </div>
</div>

<div class="control-group">
    <%= ef.label :password, :class=>"control-label" %>
   <div class="controls">
    <%= ef.password_field :password %>
  </div>
</div>

<div class="control-group">
    <%= ef.label :password_confirmation, :class=>"control-label" %>
   <div class="controls">
    <%= ef.password_field :password_confirmation %>
  </div>
</div>

<%- end %>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :fecha_nac %><br />
    <%= f.date_select :fecha_nac, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :fec_in %><br />
    <%= f.date_select :fec_in, :start_year => 1950 %>
  </div>
  <div class="field">
    <%= f.label :telefono1 %><br />
    <%= f.text_field :telefono1 %>
  </div>
  <div class="field">
    <%= f.label :telefono2 %><br />
    <%= f.text_field :telefono2 %>
  </div>
  <div class="field">
    <%= f.label :telefono3 %><br />
    <%= f.text_field :telefono3 %>
  </div>
 <div class="field">
    <%= f.label :estatus %><br />
	<select id="estatus" name="estatus">
	  <option value="1">ACTIVO</option>
	  <option value="0">BAJA</option>
	  <option value="0">BLOQUEADO</option>
	</select>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Maestros</h1>

<table class="table table-striped table-bordered table-condensed" style="table-layout:fixed;word-wrap:break-word;">
  <tr>
	<th style="text-align:center;">Nomina</th>
    <th style="text-align:center;">Nombre</th>
    <th></th>
    <th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
	<td style="text-align:center;"><%= link_to teacher.user.username, teacher %></td>
    <td style="text-align:center;"><%= teacher.nombre + " " + teacher.appat + " " + teacher.apmat %></td>
    <td width="75"><%= link_to '<i class="icon-edit icon-white"></i> Editar'.html_safe, edit_teacher_path(teacher), :class => 'btn btn-info' %></td>
    <td width="87"><%= link_to '<i class="icon-trash icon-white"></i> Eliminar'.html_safe, teacher, method: :delete, :class => 'btn btn-danger' , data: { confirm: '¿Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '<i class="icon-pencil icon-white"></i> Agregar Maestro'.html_safe, new_teacher_path, :class => 'btn btn-info' %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Apmat:</b>
  <%= @teacher.apmat %>
</p>

<p>
  <b>Appat:</b>
  <%= @teacher.appat %>
</p>


<p>
  <b>Direccion:</b>
  <%= @teacher.direccion %>
</p>

<p>
  <b>Fecha nac:</b>
  <%= @teacher.fecha_nac %>
</p>

<p>
  <b>Nombre:</b>
  <%= @teacher.nombre %>
</p>

<p>
  <b>Tel. Casa:</b>
  <%= @teacher.telefono1 %>
</p>

<p>
  <b>Tel. Celular:</b>
  <%= @teacher.telefono2 %>
</p>

<p>
  <b>Tel. Trabajo:</b>
  <%= @teacher.telefono3 %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>